TRUNCATE TABLE "User" CASCADE;
TRUNCATE TABLE "Book" CASCADE;
TRUNCATE TABLE "Order" CASCADE;
TRUNCATE TABLE "ChatRoom" CASCADE;
TRUNCATE TABLE "Message" CASCADE;
TRUNCATE TABLE "UserChatRoom" CASCADE;
TRUNCATE TABLE "Favorite" CASCADE;
TRUNCATE TABLE "BookImage" CASCADE;